apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  purpose: Inception-demo
  env : Prod

replicas:
 - name: productcatalogue
   count: 3
 - name: shopfront
   count: 3

patches:
#  - target:
#      kind: Service
#      name: productcatalogue
#    patch: |-
#      - op: replace
#        path: /spec/ports/0/port
#        value: 8031
#  - target:
#      kind: Service
#      name: shopfront
#    patch: |-
#      - op: replace
#        path: /spec/ports/0/port
#        value: 8030
  - target:
      kind: Deployment
      name: productcatalogue
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: '6255/productcatalouge-image:8071489803ef88aefecac9401effb2b682204537'
  - target:
      kind: Deployment
      name: shopfront
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: '6255/shopfront-image:8071489803ef88aefecac9401effb2b682204537'

